# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 801fa34ea41741fd7b166d41eb774207be25a979c02e606b4e3676769b428deac556c81d07e8a29e1d87ff08326341cdd6a0e2dd1450e89822974576aaa56cad

test:
  secret_key_base: 416c8362f7a61cab255945691684e31302562aef5f43e57f0fc1e68f41f7e146c07a1bc347babe7fe7067f837b9f0986314aadeeafed285a343b6b4213dcd227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
